name: 🛠 iOS CI Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔐 Setup security (macOS keychain for certs/profiles)
        run: |
          security create-keychain -p "" ios-build.keychain
          security default-keychain -s ios-build.keychain
          security unlock-keychain -p "" ios-build.keychain
          security set-keychain-settings

      - name: 🍺 Install dependencies
        run: |
          brew install xcodegen swiftlint

      - name: 📦 Resolve Swift Package Manager dependencies
        run: swift package resolve

      - name: 🧰 Restore Xcode derived data cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-derived-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-xcode-derived-

      - name: 🛠 Generate Xcode project
        run: xcodegen

      - name: 🧼 Apply SwiftFormat
        run: swiftformat . --swiftversion 5.0 --exclude build_output

      - name: 🧼 Lint Swift code
        run: swiftlint --strict || true

      - name: 🧼 Swift format check
        run: swiftformat . --lint --verbose --exclude build_output

      - name: 📊 Static analysis
        run: swiftlint analyze --strict || true

      - name: 🧹 Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: 🔖 Set app version and build number
        run: |
          echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          echo "BUILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "GIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 🧪 Build app for iOS Simulator
        run: |
          xcodebuild clean build \
            -project iosChallenge.xcodeproj \
            -scheme iosChallenge \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build_output \
            CODE_SIGNING_ALLOWED=NO \
            MARKETING_VERSION=1.0.0 \
            CURRENT_PROJECT_VERSION=$BUILD_NUMBER

      - name: 🏗 Rename output .app
        run: |
          OUTPUT_NAME="iosChallenge-${BUILD_NUMBER}.0.0-${GIT_SHORT_SHA}.app"
          mv build_output/Build/Products/Debug-iphonesimulator/iosChallenge.app \
            build_output/Build/Products/Debug-iphonesimulator/$OUTPUT_NAME

      - name: 📤 Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: build_output/Build/Products/Debug-iphonesimulator/*.app

      - name: ✅ Done
        run: echo "✅ CI Build & Artifact Export Completed!"
