name: 🛠 iOS CI Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  ci-dev:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🍺 Install dependencies
        run: |
          brew install xcodegen swiftlint swiftformat

      - name: 📦 Resolve Swift Package Manager dependencies
        run: swift package resolve

      - name: 🛠 Generate Xcode project
        run: xcodegen

      - name: 🧼 Apply SwiftFormat
        run: swiftformat . --swiftversion 5.0 --exclude build_output

      - name: 🧼 Lint Swift code
        run: swiftlint --strict || true

      - name: 📊 Static analysis
        run: swiftlint analyze --strict || true

      - name: 🏷️ Calculate next version
        id: versioning
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          VERSION=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
            ((MAJOR++))
            MINOR=0
            PATCH=0
          elif [[ "$GITHUB_REF" == "refs/heads/develop" ]]; then
            ((MINOR++))
            PATCH=0
          else
            ((PATCH++))
          fi
          NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New version: $NEW_TAG"

      - name: 🧪 Build app for iOS Simulator
        run: |
          xcodebuild clean build \
            -project iosChallenge.xcodeproj \
            -scheme iosChallenge \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build_output \
            CODE_SIGNING_ALLOWED=NO \
            MARKETING_VERSION=1.0.0 \
            CURRENT_PROJECT_VERSION=$NEW_TAG

      - name: 🏷️ Create Git Tag
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: 🏗 Rename output .app
        run: |
          OUTPUT_NAME="iosChallenge-${NEW_TAG}-dev.app"
          mv build_output/Build/Products/Debug-iphonesimulator/iosChallenge.app \
            build_output/Build/Products/Debug-iphonesimulator/$OUTPUT_NAME

      - name: 📤 Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: build_output/Build/Products/Debug-iphonesimulator/*.app

      - name: ✅ Done
        run: echo "✅ CI Build & Artifact Export Completed!"
